name: MCRussianRoulette
version: '${version}'
main: io.github.titanthemoon.mcrussianroulette.MCRussianRoulette
api-version: 1.17
authors: [ titanthemoon ]
description: Add russian roulette to your minecraft server!
commands:
  getrrbow:
    description: Get A Russian Roulette Bow
    permission: russianroulette.getrrbow
  getrrkit:
    description: Get a randomized pvp kit
    permission: russianroulette.getkit
